[book]
authors = ["Jaron Zijlstra"]
description = "NodeJS lessons created by Jaronline"
language = "en"
multilingual = false
src = "src"
title = "NodeJS"

[build]
build-dir = "target/docs"
create-missing = false