name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Check materials and publish if tagged
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2

      - name: Check links in markdown
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: 'src/'

      - name: Run mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
      - run: |
          mdbook build
      - name: Publish book website
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/docs
          keep_files: false